name: Auto-update version and release

on:
  push:
    branches:
      - main

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          
      - name: Auto-update version and commit changes
        run: |
          npm install -g npm-version-up
          npm-version-up patch
          git config --local user.name "developer-impetus"
          git config --local user.email "developer@impetus.bet"
          git add package.json
          git commit -m "Auto-update version"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true